name: E2E tests

on:
  workflow_run:
    workflows: ['Build project']
    types: [completed]

jobs:
  e2e_tests:
    name: Run E2E tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}


    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGODB_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGO_INITDB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 3

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js for testss
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm ci

      - name: Run e2e tests
        env:
          MONGODB_HOST: ${{ secrets.MONGODB_HOST }}
          MONGODB_PORT: ${{ secrets.MONGODB_PORT }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
          MONGODB_USER: ${{ secrets.MONGODB_USER }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        run: npm run test:e2e
      - name: Fail if E2E tests fail
        if: failure()
        run: exit 1

      - name: Report status to PR
        if: success()
        run: |
          gh api repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_sha }} \
            -X POST \
            -F state=success \
            -F context="E2E Tests raport" \
            -F description="E2E tests passed successfully"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Report failure to PR
        if: failure()
        run: |
          gh api repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_sha }} \
          -X POST \
          -F state=failure \
          -F context="E2E Tests raport" \
          -F description="E2E tests failed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
  report-skipped:
    name: Report Skipped Status
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Report skipped to PR
        run: |
          gh api repos/${{ github.repository }}/check-runs \
          -X POST \
          -F name="E2E Tests raport" \
          -F head_sha="${{ github.event.workflow_run.head_sha }}" \
          -F status="completed" \
          -F conclusion="failure" \
          -F output[title]="E2E Tests Skipped" \
          -F output[summary]="E2E Tests were skipped due to failure in Build Project."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
